In [2]:
import numpy as np
a = np.array([4,5,6,7,8,9])
a

array([4, 5, 6, 7, 8, 9])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = a*2
b

array([ 8, 10, 12, 14, 16, 18])

In [5]:
c = a**2
c

array([16, 25, 36, 49, 64, 81])

In [6]:
k = np.array([[4,6,8],[2,4,7],[4,8,1],[3,6,7],[1,7,4]])
k

array([[4, 6, 8],
       [2, 4, 7],
       [4, 8, 1],
       [3, 6, 7],
       [1, 7, 4]])

In [15]:
print('ndim: ', k.ndim)
print('shape: ', k.shape)
print('itemsize: ', k.itemsize)
print('size: ', k.size)
print('data: ', k.data)
print('nbytes: ', k.nbytes)
print('stides: ', k.strides)
print('falgs: \n', k.flags)

ndim:  2
shape:  (5, 3)
itemsize:  8
size:  15
data:  <memory at 0x0000027E281CCBA0>
nbytes:  120
stides:  (24, 8)
falgs: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [16]:
j = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]],[[28,29,30],[31,32,33],[34,35,36]],[[37,38,39],[40,41,42],[43,44,45]]])
j

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])

In [8]:
import numpy as np

q = np.zeros((3,3))
p = np.ones((3,4), dtype = int)
r = np.empty((2,2), dtype = int)
s = np.full((3,3), 22)

print(q)
print(p)
print(r)
print(s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[   4294967296 1773821493248]
 [         1480   85899346688]]
[[22 22 22]
 [22 22 22]
 [22 22 22]]


In [11]:
import numpy as np

t = np.eye(3,3,-1,dtype = int)
print(t)

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [13]:
u = np.fromstring('23 45 67 231 12 12', sep = ' ', dtype = int )
print(u)

[ 23  45  67 231  12  12]


In [14]:
k = np.random.randint(2,9,size = (3,4))
print(k)

[[3 3 3 3]
 [2 3 7 7]
 [5 6 3 5]]


In [16]:
print(np.sqrt(k))

[[1.73205081 1.73205081 1.73205081 1.73205081]
 [1.41421356 1.73205081 2.64575131 2.64575131]
 [2.23606798 2.44948974 1.73205081 2.23606798]]


In [20]:
print(np.where(k >= 3))

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 1, 2, 3, 0, 1, 2, 3]))


In [54]:
import numpy as np
a = np.random.randint(6,20,size=(4,4))

# b = np.random.rand(2,3)*7
# c = np.eye(3, 4)
# p = np.zeros((2,2))
# q = np.ones((2,2))
# r = np.fromstring('1 2 3 4 5 6 7',sep=' ', dtype=int)
# s = np.full((3,4),4)
# t = np.arange(2,20,2)


print(a)
print('max: ', np.max(a))
print('sum: ', np.sum(a))
print('min: ', np.min(a))
print('prod: ', np.prod(a))

print('Condition: ', np.where(a >15) )
print('Condition: ', np.where(a % 2 == 0) )

# print(b)
# print(c)
# print(p)
# print(q)
# print(r)
# print(s)
# print(t)
# print(np.sqrt(s))
# print(np.max(r))
# print(np.max(s))

[[16 18 18 18]
 [ 6 13 11 19]
 [15 15  8 14]
 [16 10  9 15]]
max:  19
sum:  221
min:  6
prod:  828004464967680000
Condition:  (array([0, 0, 0, 0, 1, 3]), array([0, 1, 2, 3, 3, 0]))
Condition:  (array([0, 0, 0, 0, 1, 2, 2, 3, 3]), array([0, 1, 2, 3, 0, 2, 3, 0, 1]))


In [64]:
m = np.random.randint(2,8,size=(2,2))
n = np.random.randint(2,6,size=(2,2))

print(m)
print()
print(n)
print()

print(m*n) # Manual way se multiply krta

[[2 3]
 [4 7]]

[[5 5]
 [5 2]]

[[10 15]
 [20 14]]


In [67]:
m = np.random.randint(2,8,size=(3,4))
print(m)
print()
print(np.cumsum(m))
print(np.isnan(m))

[[3 7 7 3]
 [2 7 7 6]
 [4 6 3 7]]

[ 3 10 17 20 22 29 36 42 46 52 55 62]
[[False False False False]
 [False False False False]
 [False False False False]]


In [70]:
i = np.random.randint(2,20,size=(3,4))
j = np.random.randint(2,20,size=(3,4))

print(i)
print()
print(j)
print()
print(i > j)

[[13 16  9  7]
 [10 19  6  4]
 [ 7 13 16 14]]

[[ 3  7  3  4]
 [17  7 19  5]
 [18  5  3 15]]

[[ True  True  True  True]
 [False  True False False]
 [False  True  True False]]


In [71]:
i = np.random.randint(2,20,size=(3,4))


print(i)

print()
print(np.where(i%2==0,'true','false'))

[[15 16 14 14]
 [ 4 12  7 18]
 [ 3 16  5  2]]

[['false' 'true' 'true' 'true']
 ['true' 'true' 'false' 'true']
 ['false' 'true' 'false' 'true']]


In [78]:
arr = np.array([2,4,6,7,8,9,3])
print(arr[-3])
print(arr[4])

8
8


In [1]:
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
ray = np.array(mylist)
np

NameError: name 'np' is not defined

In [7]:
import numpy as np
myList =  [
           [ [1, 2, 3, 4], [5, 6, 7, 8], [1, 3, 5, 6] ],
           [ [3, 5, 6, 8], [3, 4, 5, 6], [2, 4, 6, 8] ],
          ]
arr = np.array(myList)
arr


array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 3, 5, 6]],

       [[3, 5, 6, 8],
        [3, 4, 5, 6],
        [2, 4, 6, 8]]])

In [9]:
print(arr[1])
print(arr[1][2])
print(arr[1][2][3])

[[3 5 6 8]
 [3 4 5 6]
 [2 4 6 8]]
[2 4 6 8]
8


In [26]:
arr_1 = [2, 3, 5, 6, 9, 4, 7]
print(arr_1[::-1])
print(arr_1[2:5])
print(arr_1[-2:-5:-1])


[7, 4, 9, 6, 5, 3, 2]
[5, 6, 9]
[4, 9, 6]


In [31]:
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print(arr[2:,:3])
print(arr[])

[[3 2 4]
 [7 3 4]
 [4 0 3]]


In [4]:
import numpy as np
arr = np.array([2,3,4,5,6,7,7,4,4])
print(arr[1:-5])
print(arr[-1:-5:-1])
print(arr[-1:2:-1])

[3 4 5]
[4 4 7 7]
[4 4 7 7 6 5]


In [15]:
ar = np.random.randint(2,20,size = (3,3,3))
print(ar)
print(ar[:1:,:2:,:1:])
print(ar[:2:,:2:,:1:])
print(ar[:1:,:1:,:3:])
print(ar[:3:,:3:,2:3:])

[[[12 15 13]
  [17 11 16]
  [13 15  3]]

 [[ 9 15  5]
  [16  7  4]
  [18  4 10]]

 [[ 5 19  5]
  [ 7  5 14]
  [ 5  3 18]]]
[[[12]
  [17]]]
[[[12]
  [17]]

 [[ 9]
  [16]]]
[[[12 15 13]]]
[[[13]
  [16]
  [ 3]]

 [[ 5]
  [ 4]
  [10]]

 [[ 5]
  [14]
  [18]]]


In [23]:
arr = np.random.randint(1,101,10)
print(arr)
print(arr[[0,4,7,5]])
print(arr>50)
print(arr[arr>50])


[38 32 35 90 50 59 28 56  4 24]
[38 50 56 59]
[False False False  True False  True False  True False False]
[90 59 56]


In [28]:
arr = np.random.randint(1,101,(3,3))
print(arr)
rows_wanted = np.array([True,False,True])
cols_wanted = np.array([False,True,False])
print(arr[rows_wanted,:])
print(arr[:,cols_wanted])

[[25 33 44]
 [97 81 93]
 [ 8 95 72]]
[[25 33 44]
 [ 8 95 72]]
[[33]
 [81]
 [95]]
