In [6]:
#                                                         BroadCasting
import numpy as np
arr_1 = np.random.randint(1,51,size=(3,4))
arr_2 = np.random.randint(1,51,size=(3,1))
print(arr_1)
print(arr_2)
print(arr_1+arr_2)

[[21 18 22 36]
 [ 1 25 12 40]
 [ 8 34 40 28]]
[[33]
 [12]
 [50]]
[[54 51 55 69]
 [13 37 24 52]
 [58 84 90 78]]


In [7]:
arr_1 = np.random.randint(1,51,size=(3,4))
arr_2 = np.random.randint(1,51,size=(1,4))
print(arr_1)
print(arr_2)
print(arr_1+arr_2)

[[14 41 25 26]
 [36  7 29 16]
 [22  7 29 22]]
[[41 13 23 10]]
[[55 54 48 36]
 [77 20 52 26]
 [63 20 52 32]]


In [8]:
arr_1 = np.random.randint(1,51,size=(3,4))
arr_2 = np.random.randint(1,51,size=(4,1))
print(arr_1)
print(arr_2)
print(arr_1+arr_2)

[[35 28 25 31]
 [ 1 11 12 24]
 [45  3 15 14]]
[[ 8]
 [ 2]
 [26]
 [20]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [9]:
arr_1 = np.random.randint(1,51,size=(3,4))
arr_2 = np.random.randint(1,51,size=(1,3))
print(arr_1)
print(arr_2)
print(arr_1+arr_2)

[[ 9  2 24  8]
 [11 15 32 46]
 [12 15  8  7]]
[[38 15 43]]


ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [13]:
#                                                   Reshaping

arr = np.arange(24)
print(arr)
arr.shape = (3,8)
print(arr)
arr.shape = (2,4,3)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [24]:
arr = np.random.randint(2,21,size=(3,4))
print('(3,4) \n',arr)
arr_1 = np.reshape(arr,(6,2))
print('(6,2) \n',arr_1)
arr_2 = np.reshape(arr,(12,1))
print('(12,1) \n',arr_2)
np.reshape(arr,(8,2))  #that makes it different from resize
print('(8,2) \n',arr_3)

(3,4) 
 [[ 4  2  7 18]
 [16 16 20 15]
 [ 9 10  6 11]]
(6,2) 
 [[ 4  2]
 [ 7 18]
 [16 16]
 [20 15]
 [ 9 10]
 [ 6 11]]
(12,1) 
 [[ 4]
 [ 2]
 [ 7]
 [18]
 [16]
 [16]
 [20]
 [15]
 [ 9]
 [10]
 [ 6]
 [11]]


ValueError: cannot reshape array of size 12 into shape (8,2)

In [23]:
arr = np.random.randint(2,21,size=(3,4))
print('(3,4) \n',arr)
arr_1 = np.resize(arr,(6,2))
print('(6,2) \n',arr_1)
arr_2 = np.resize(arr,(12,1))
print('(12,1) \n',arr_2)
arr_3 = np.resize(arr,(8,2))  #Don't give any error
print('(8,2) \n',arr_3)

(3,4) 
 [[17 12 16 12]
 [ 9  6  2 11]
 [11  2 20 11]]
(6,2) 
 [[17 12]
 [16 12]
 [ 9  6]
 [ 2 11]
 [11  2]
 [20 11]]
(12,1) 
 [[17]
 [12]
 [16]
 [12]
 [ 9]
 [ 6]
 [ 2]
 [11]
 [11]
 [ 2]
 [20]
 [11]]
(8,2) 
 [[17 12]
 [16 12]
 [ 9  6]
 [ 2 11]
 [11  2]
 [20 11]
 [17 12]
 [16 12]]


In [26]:
#                                                         Transpose

arr = np.arange(12)
print(arr)
print(arr.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
arr = np.random.randint(2,12,size=(3,4))
print(arr)
print(arr.transpose())

[[ 7  4  7  6]
 [ 4  8  2  4]
 [11  9  6 11]]
[[ 7  4 11]
 [ 4  8  9]
 [ 7  2  6]
 [ 6  4 11]]


In [36]:
arr = np.random.randint(2,12,size=(3,1,2))
print(arr,arr.shape,end='\n',sep=' ')
new_arr = arr.transpose()
print(new_arr,new_arr.shape,end='\n',sep=' ')

[[[ 3 11]]

 [[ 3  5]]

 [[ 4  9]]] (3, 1, 2)
[[[ 3  3  4]]

 [[11  5  9]]] (2, 1, 3)


In [41]:
#                                             SwapAxes & Flatten
arr = np.random.randint(2,12,size=(3,1,2))
arr_2 = np.swapaxes(arr,0,2)
print(arr)
print(arr_2.shape,'\n',arr_2)
arr_3 = arr.flatten(order = 'C')
print(arr_3)
arr_3 = arr.flatten(order = 'F')
print(arr_3)

[[[10  3]]

 [[ 5  2]]

 [[ 8 10]]]
(2, 1, 3) 
 [[[10  5  8]]

 [[ 3  2 10]]]
[10  3  5  2  8 10]
[10  5  8  3  2 10]


In [49]:
#                                          Sorting
arr = np.random.randint(2,21,size = 10)
print(arr)
arr_2 = np.sort(arr,kind = 'quicksort')
print(arr_2)
arr_3 = np.sort(arr,kind = 'headsort')
print(arr_3)
arr_4 = np.sort(arr,kind = 'mergeksort')
print(arr_4)

[ 6 19 12 16 13 16 12 18 12  7]
[ 6  7 12 12 12 13 16 16 18 19]
[ 6  7 12 12 12 13 16 16 18 19]
[ 6  7 12 12 12 13 16 16 18 19]


In [51]:
arr = np.random.randint(2,21,size =(4,3))
print(arr)
arr_2 = np.sort(arr,axis=None)
print(arr_2)
arr_3 = np.sort(arr,axis=0)
print(arr_3)
arr_4 = np.sort(arr,axis=1)
print(arr_4)

[[ 5  4  9]
 [15  9  9]
 [13  8  7]
 [11 18  2]]
[ 2  4  5  7  8  9  9  9 11 13 15 18]
[[ 5  4  2]
 [11  8  7]
 [13  9  9]
 [15 18  9]]
[[ 4  5  9]
 [ 9  9 15]
 [ 7  8 13]
 [ 2 11 18]]


In [53]:
arr = np.random.randint(2,21,size =(2,3,3))
print(arr)
arr_2 = np.sort(arr,axis=None)
print(arr_2)
arr_3 = np.sort(arr,axis=0)
print(arr_3)
arr_4 = np.sort(arr,axis=1)
print(arr_4)
arr_5 = np.sort(arr,axis=2)
print(arr_5)

[[[20 17  4]
  [18 17 19]
  [12  2 10]]

 [[13  9  3]
  [ 5  8 19]
  [ 5 14  6]]]
[ 2  3  4  5  5  6  8  9 10 12 13 14 17 17 18 19 19 20]
[[[13  9  3]
  [ 5  8 19]
  [ 5  2  6]]

 [[20 17  4]
  [18 17 19]
  [12 14 10]]]
[[[12  2  4]
  [18 17 10]
  [20 17 19]]

 [[ 5  8  3]
  [ 5  9  6]
  [13 14 19]]]
[[[ 4 17 20]
  [17 18 19]
  [ 2 10 12]]

 [[ 3  9 13]
  [ 5  8 19]
  [ 5  6 14]]]
